// src/system/interceptors/logging.interceptor.ts

/**
 * @description This module is an interceptor that calculates the duration
 * of a request and logs the end of this request.
 * The correlationId is generated by the correlationId Middleware.
 * This same middleware stores the ID in the ALS.
 * The ALS acts as a bridge between the middleware and the interceptor.
 */

import {
	CallHandler,
	ExecutionContext,
	Injectable,
	NestInterceptor,
	HttpException,
} from '@nestjs/common';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { Request, Response } from 'express';
import { WinstonLoggerService } from '../../logger/logger-service/winston-logger.service.js';
import { Histogram, Counter } from 'prom-client';

@Injectable()
export class LoggingInterceptor implements NestInterceptor {
	/*  Prometheus metrics for HTTP requests */
	private static readonly httpRequestsTotal = new Counter({
		name: 'http_requests_total',
		help: 'Nombre total de requêtes HTTP',
		labelNames: ['method', 'path', 'status'],
	});

	private static readonly httpRequestDuration = new Histogram({
		name: 'http_request_duration_ms',
		help: 'Durée des requêtes HTTP en ms',
		labelNames: ['method', 'path', 'status'],
		buckets: [50, 100, 200, 500, 1000, 2000, 5000], // Latency buckets in milliseconds
	});

	constructor(private readonly loggerService: WinstonLoggerService) {}

	intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
		const now = Date.now();
		const request: Request = context.switchToHttp().getRequest();

		if (request.url === '/metrics') {
			return next.handle(); // Skip logging for Prometheus metrics endpoint
		}

		return next.handle().pipe(
			tap({
				next: () => {
					const response: Response = context.switchToHttp().getResponse();
					this.updateMetrics(request, response.statusCode, now); // Prometheus
					this.logRequest(request, response.statusCode, now); // Winston/Mongo
				},
				error: (err: unknown) => {
					const errorData = err
						? this.getErrorData(err)
						: this.getErrorData(new Error('Unknown error'));
					this.updateMetrics(request, errorData.statusCode, now); // Prometheus
					this.logRequest(request, errorData.statusCode, now, errorData); // Winston/Mongo
				},
			}),
		);
	}

	private updateMetrics(
		request: Request,
		statusCode: number,
		startTime: number,
	) {
		const latency = Date.now() - startTime;
		const path = (request.route as { path: string })?.path || 'unmatched_route';
		// Do not use request.url directly as it contains query parameters.
		// Multiple records would be created for the same route, generating high cardinality and performance issues.

		LoggingInterceptor.httpRequestsTotal
			.labels(request.method, path, statusCode.toString())
			.inc();

		LoggingInterceptor.httpRequestDuration
			.labels(request.method, path, statusCode.toString())
			.observe(latency);
	}

	private logRequest(
		request: Request,
		statusCode: number,
		startTime: number,
		errorData?: { message: string; statusCode: number; stack?: string },
	) {
		const latency = Date.now() - startTime;
		const message = `Requête ${errorData ? 'échouée' : 'terminée'}`;

		if (errorData) {
			this.loggerService.error(errorData.message, errorData.stack, {
				method: request.method,
				url: request.url,
				statusCode: errorData.statusCode,
				latency: `${latency}ms`,
			});
		} else {
			this.loggerService.log(message, {
				method: request.method,
				url: request.url,
				statusCode: statusCode,
				latency: `${latency}ms`,
			});
		}
	}
	/** Helper that retrieves error message, code and stack */
	getErrorData(error: unknown): {
		message: string;
		statusCode: number;
		stack?: string;
	} {
		let statusCode: number;
		let errorMessage: string;
		let stack: string | undefined;
		if (!error) {
			return {
				message: 'Unknown error',
				statusCode: 500,
				stack: undefined,
			};
		}
		if (error instanceof HttpException) {
			statusCode = error.getStatus();
			errorMessage = error.message;
			stack = error.stack;
		} else if (error instanceof Error) {
			statusCode = 500;
			errorMessage = error.message;
			stack = error.stack;
		} else {
			statusCode = 500;
			errorMessage = 'Unknown error';
			stack = undefined;
		}
		return {
			message: errorMessage,
			statusCode,
			stack,
		};
	}
}
